### ISSUE TITLE
Degust re-uses condition colours

### ISSUE THREAD

**Issue by aabarug** [drpowell/degust#1]
If more than ten conditions are added in Degust, then the last samples use the same colours as the first samples

**Comment by dontflytiger** [comment]
This can be fixed by changing lines 70 and 107 in `qc.coffee` to use the 20 colour scheme. [See here for reference. ](http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d)

Not an expert in javascript so please excuse this post if it's incorrect.

**Comment by ammaraziz** [comment]
This can be fixed by changing lines 70 and 107 in `qc.coffee` to use the 20 colour scheme. [See here for reference. ](http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d)

Not an expert in javascript so please excuse this post if it's incorrect.

**Comment by drpowell** [comment]
It's actually set in compare.coffee:322
I could change it there, but the 20 colour scheme seems much worse when there are few samples.  So, I'd like to make it dynamically select colour scheme depending on the number of samples

**Comment by drpowell** [comment]
Done in new vue refactor
