### ISSUE TITLE
Generate TMM for Edge R DE analysis by using Degust

### ISSUE THREAD

**Issue by r06442015** [drpowell/degust#106]
How to generate EdgeR’s trimmed mean of M values (TMM) by using Degust instead of CPM

**Comment by drpowell** [comment]
Unfortunately you cannot currently export TMM from Degust.  It will use TMM internally for DE testing, or for the MDS (when "backend normlised" is selected).  Currently the best solution is to have degust export the R code, then modify that to save the TMM.

**Comment by r06442015** [comment]
I have another question about the cpm function.
I’ve tried to look up in R conduct cpm function. The default setting is using normalized library, which can represent TMM as well. Does the export file of cpm by Degust use the normalized library?

Benjamin Du

**Comment by drpowell** [comment]
Degust calculates the cpm by dividing by library size, and multiplying by 1e6.  It also does a log2-transform of this with a with a prior-count (or log moderation) of 10.  This is different to cpm() from edgeR which uses a default of 0.25.  The reason for this difference, is that degust only uses the cpm for visualisation and the larger moderation is appropriate to better stabilise the variances.  For the differential expression testing, the typical TMM and cpm() is used.

**Comment by r06442015** [comment]
Thanks for sharing these details that I would not notice the difference of prior count. I would like to make sure that if I choose Edge R method in degust the cpm is generate directly from raw count or from TMM? Since I am quite confuse by the same name with different function.
And, Thanks for your help, I am still learning R as well, so it is a little challenging for me.
https://www.biostars.org/p/317701/
Benjamin Du
