### ISSUE TITLE
How is logFC relative to Average computed?

### ISSUE THREAD

**Issue by mauriciolangleib** [drpowell/degust#107]
Hi! First of all, many thanks for developing this great tool. 

I'm writting because I can't reproduce the logFC values that I get when perfoming analysis setting the "logFC relative to" to the "Average" option. 

To be a bit more specific, for a given gene, logFC relative to Average is said to be 6.78. When I take the CPM values for that gene and try to reproduce this logFC value, I can't manage to do it! 

So, how is this value computed? My intuition was that it must somehow take the CPM values of the given condition and calculate the FC relative to the average expression of the gene, but there must be something that I am missing (as performing that computation for this gene don't match with the shown values).

Hope I was clear, many thanks in advance!

Cheers,
Mauricio

**Comment by drpowell** [comment]
The logFC values are computed in R using the currently selected tool - eg. voom/limma, or edgeR.  

To display "logFC relative to 'Average'" these logFC values are simply averaged for each gene.  For example, in the case where you have 3 conditions X, Y, Z the R calculation will return 2 logFC values - say, logFC of Y, and logFC of Z and we will set logFC X=0 (all relative to X).  To display relative to average, `avg(Y) = Y-(X+Y+0)/3`,  `avg(Z) = Y-(X+Y+0)/3`, `avg(X) = 0 - (X+Y+0)/3`.   Further, these 3 values will sum to zero.
