### ISSUE TITLE
Degust server missing RUVSeq package

### ISSUE THREAD

**Issue by emmarcotte** [drpowell/degust#122]
Hi,

We're big fans of the Degust public web server and have been using it for several months now across a range of (proteomics) projects. It's throwing an error today indicating a problem with the RUVSeq package:

"Error in library(RUVSeq) : there is no package called 'RUVSeq'
Execution halted"

Many thanks for a wonderful server & software package,
Edward Marcotte
University of Texas at Austin

**Comment by drpowell** [comment]
I had to update to a new version of bioconductor, but it seems I didn't test RUVSeq. 
Thanks for the report.

**Comment by drpowell** [comment]
This should be working again.
