### ISSUE TITLE
File upload 'Info columns' format requirements 

### ISSUE THREAD

**Issue by calizilla** [drpowell/degust#123]
I uploaded a counts file which had 3 gene annotation fields as the last 3 columns of the CSV.  I assigned these columns as 'Info columns' along with 'Gene name'.  This produced the fatal error `NA counts not allowed`. It turns out these annotation columns must be positioned right after the Gene Name column, and before the counts. It would be great to add this format requirement to the Uploads page.

**Comment by drpowell** [comment]
It shouldn't be necessary to order the columns like that.  Do you have a csv file you can share?

**Comment by calizilla** [comment]
[Degust_issue.zip](https://github.com/user-attachments/files/17122280/Degust_issue.zip)

Thanks for your reply. The link contains a tiny CSV with and without the annotations columns, along with a screenshot of the error.

**Comment by drpowell** [comment]
Thanks for the report.  I am unable to reproduce the problem with your cutdown csv.
But I can see that your original csv file has some problems.  Specifically, the rows for these "genes"
[1] "LOC123411033" "LOC123447673" "LOC123447674" "LOC123447675"
All have a bare comma in the last MEROPS column.  It should work if you fix the csv formatting to wrap the last field in double-quotes.

I would like to add better csv error checking and reporting to degust
