### ISSUE TITLE
question on the csv output

### ISSUE THREAD

**Issue by khoojj** [drpowell/degust#125]
Hi, I am new to DE analyses.
I have run the analyses on the DEGUST web app with my count matrix, using VOOM/LIMMA method.
I downloaded the Genes table at the MA plot tab. May I know what are the numbers under the sample names?
Are they CPM for each sample? I noticed I have 2 sets of columns with my samples and different numbers below. 
Attached is the example of the output.

Thank you.
[example.xlsx](https://github.com/user-attachments/files/16996252/example.xlsx)

**Comment by drpowell** [comment]
Yes, those will be CPM values - that are just normalised for library size.
