### ISSUE TITLE
Attempting to save 3D MDS view causes browser freeze

### ISSUE THREAD

**Issue by swbioinf** [drpowell/degust#13]
When viewing a 3D MDS plot, it is possible to right click to save as PNG/SVG. This causes a session crash with a unresponsive box - clicking the menu options will escape but it does loose memory of what samples were selected e.t.c.

I suspect this shouldn't be an option at all.

Also occurs if animation has been toggled off.

**Comment by drpowell** [comment]
PNG printing should be fixed : bf986923c2d6ac7ca1d42bfa2e5fc6d0d7529e65
