### ISSUE TITLE
Quasi-likelihood method throws error on example data

### ISSUE THREAD

**Issue by claresloggett** [drpowell/degust#14]
The new edgeR quasi-likelihood method is throwing an R error on the example data on the server. I haven't tested on other data.

That is, I reach this error via

http://degust.erc.monash.edu/ -> Play with a demo -> edgeR quasi-likelihood -> Apply

**Comment by drpowell** [comment]
It's a bad sign it doesn't work on the example.  It does work on other sets.  Something in the R doesn't like there only being 1 DE gene.  Not sure what it is yet.  Thanks for reporting. 

(That example data set is bad, really need a better one.)

**Comment by drpowell** [comment]
Fixed upstream in edgeR
https://support.bioconductor.org/p/102373/

I'll deploy shortly.
