### ISSUE TITLE
Clean error message for 1 vs 1 analysis

### ISSUE THREAD

**Issue by AMChalkie** [drpowell/degust#2]
We all know that 1 vs 1 isn't ideal, but hey, sometimes its what we have to analyse. Clean error messaging when voom/edge fails due to this would be good. And ideally a version that also allows visualisation of such data (with all the caveats that you would expect).

**Comment by drpowell** [comment]
Good point.  I believe edgeR has a method to "work" with these, but I've not used it.  

The more general problem is when there is a linear model that is under-constrained so we can't estimate some of the parameters

**Comment by drpowell** [comment]
Added "logFC only" analysis.  Basically uses limma for the logFC, but sets FDR=1.
