### ISSUE TITLE
Enhancement: Experiment metadata / text description

### ISSUE THREAD

**Issue by AMChalkie** [drpowell/degust#22]
It would be useful to have a text box where we can include a full description of the processing done on the dataset - a materials and methods if you like. Useful to keep track of documentation within degust for easy access.

**Comment by drpowell** [comment]
There is now an option on the configure page to set a description.
a7461198a23fc8d05d3e10b62fc41f6530412b92

Still to have this display on other pages to be useful

**Comment by drpowell** [comment]
This description is now available in the dev interface on the main page
