### ISSUE TITLE
3D Mds legend possible?

### ISSUE THREAD

**Issue by methylnick** [drpowell/degust#4]
More a feature request, possible to present a legend for the 3D mds plot? (again on behalf of an interested end-user).

**Comment by drpowell** [comment]
Added labels - and not sure on space for a legend.  Best is to use the Gene strip chart in the top right

**Comment by drpowell** [comment]
8db66ca3bf8562e5856d6bb4d5f469a8df727fcb and 1578981cccf498281c2fd6e81c04d85ce6dc7f87
