### ISSUE TITLE
Basic understanding

### ISSUE THREAD

**Issue by PedroDaPos** [drpowell/degust#40]
Hi,
I was wondering what is the meaning of the color scheme in KEGG pathways - they don't match the colors given to different treatments in the MDS plot, for example. I am also wondering if it is possible to customize and save the parallel coordinates plot (e.g. select only a custom set of genes to be displayed).
Degust is a great tool, and I apologize in advance if the answers to my questions are in the Degust website, I was unable to find them.
Thank you in advance!

**Comment by drpowell** [comment]
The KEGG functionality in degust has always been somewhat experimental, and we are currently working on replacing it with more generic gene set enrichment tests.

The colours in the kegg layout are as follows:
            when 'same' then 'green'
            when 'mixed' then 'yellow'
            when 'up' then 'red'
            when 'down' then 'blue'

Here, "same" means the genes with that EC all have an absolute logFC of less than 0.1.  Up (down) means all the genes with that EC have a logFC > 0.1 (< -0.1).  And 'mixed' means the genes with that EC are a combination of this.

There is a dev version of the interface you can try if you log in.  This will allow you to limit to a custom gene set for displaying the parallel coord plot.

Thanks for the feedback.
