### ISSUE TITLE
enable batch options

### ISSUE THREAD

**Issue by AMChalkie** [drpowell/degust#42]
It would be useful if batch effects could be included in the DGE.

**Comment by drpowell** [comment]
You should able to handle batch effects with a "hidden factor".  eg. if you have 3 different batches, create a "hidden factor" for 2 of them which then adds 2 extra terms to the design matrix.

**Comment by AMChalkie** [comment]
ok great. May I suggest that some extra documentation? I notice also the screencast is from 2013 :) It would be worthwhile for those new to the software to have a bit more info, and also to show off some of the extra new cool bits that have been added.

**Comment by drpowell** [comment]
Absolutely a good idea.  I was thinking added some use-case docs for situations like batch-effects, or paired-experiments.
