### ISSUE TITLE
Can't validate p-values

### ISSUE THREAD

**Issue by jwonggit** [drpowell/degust#53]
Hi I have been trying to replicate the edgeR quasi-likelihood analysis with Degust. I managed to get the same values for logFC and logCPM but not the p-values. R-code looks alright to me. Any possible explanation to that?

Thank you.

**Comment by drpowell** [comment]
It could be R package versions?  Degust "show R code" will display the R code used, and package versions to reproduce the exact results.

**Comment by jwonggit** [comment]
My sequencing facility performed the quasi-likelihood analysis with edgeR version 3.26.5 while Galaxy uses version 3.24.1, and both of them produced the exact p-value results. I don't think it's the issue of different edgeR versions, unless there's a change in the quasi-likelihood test between version 3.26.5 and version 3.26.7 in Degust?

**Comment by drpowell** [comment]
I don't know if there are differences between those versions.  If you take the R code from from the degust "show r code" page, and the same package versions, you will reproduce the p-values exactly.  The degust visualisation does not change the p-values that come from edgeR.

**Comment by jwonggit** [comment]
Problem solved. The difference is due to the use of robust settings (robust=TRUE) from statmod package with the edgeR estimateDisp and glmQLFit functions. Would be good to have the settings included to protect against outlier genes.

**Comment by drpowell** [comment]
New issue opened for this option suggestion #61
