### ISSUE TITLE
Gene Link URL does not work

### ISSUE THREAD

**Issue by schmittst** [drpowell/degust#71]
It looks like that adding a customized Gene Link URL (I tried "http://www.pseudomonas.com/feature/show/?locus_tag=%s") does not work. The entries in the table do not contain a link after adding the URL and providing a Gene Link Column (if left blank the entries are correctly linked to NCBI).

**Comment by matrs** [comment]
I'm using the `degust.py`  and I noticed that the created HTML is linking to a rather old `js` library, so the links aren't working. Is there a chance to use `degust.py` with the latest  release?
