### ISSUE TITLE
Installation: Docker build fails at step 9/21

### ISSUE THREAD

**Issue by schmittst** [drpowell/degust#72]
I try to install degust via docker. The command "docker build . --tag degust" fails at Step 9/21 with the message:
Step 9/21 : RUN rake degust:deps     && rake degust:build     && rake assets:precompile
 ---> Running in d20ab4cd80d5
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 12.3.2. Prepending `bundle exec` to your command may solve this.

Any way to adapt this to rake 12.3.2 instead of 12.0.0?
I tried to run this on a new Centos 8.1 system.

**Comment by schmittst** [comment]
I made the following changes in the Dockerfile:

# Build the js front-end
RUN **bundle exec** rake degust:deps \
    && **bundle exec** rake degust:build \
    && **bundle exec** rake assets:precompile

Those solved the issue

**Comment by schmittst** [comment]
> 
> 
> I made the following changes in the Dockerfile:
> # Build the js front-end
> 
> RUN **bundle exec** rake degust:deps
> && **bundle exec** rake degust:build
> && **bundle exec** rake assets:precompile
> 
> Those solved the issue

But only for"build" - running still fails with the same message...

**Comment by drpowell** [comment]
Thanks for the report.  Not sure why I didn't hit this issue before
