### ISSUE TITLE
Twitter Auth appears to be broken

### ISSUE THREAD

**Issue by mmsee** [drpowell/degust#86]
Hi Dave, 

The Twitter auth appears to be broken, producing "We're sorrybut something went wrong" message 😅 

![image](https://user-images.githubusercontent.com/13144756/91508427-d75f7400-e91a-11ea-853b-d5c0e357ae31.png)

Both Google and GitHub sign in appears to behave

**Comment by drpowell** [comment]
Fixed - I needed to update the twitter end since switching to `https`.

Thanks.
