### ISSUE TITLE
Selecting view after save changes produces error (ok when view from config screen)

### ISSUE THREAD

**Issue by AMChalkie** [drpowell/degust#9]
Bit of a strange error this one. Using chrome.

settings=%7B%22csv_format%22%3Atrue%2C%22replicates%22%3A%5B%5B%22KI%22%2C%5B%22S232_KIr%22%2C%22S233_KIr%22%2C%22S242_KIr%22%5D%5D%2C%5B%22WT%22%2C%5B%22S176_WTr%22%2C%22S225_WTr%22%2C%22S228_WTr%22%5D%5D%5D%2C%22fc_columns%22%3A%5B%5D%2C%22info_columns%22%3A%5B%22Gene+ID%22%2C%22gene_biotype%22%2C%22name%22%2C%22entrezgene%22%2C%22chromosome_name%22%2C%22start_position%22%2C%22end_position%22%2C%22strand%22%2C%22Length%22%2C%22description%22%5D%2C%22analyze_server_side%22%3Atrue%2C%22link_column%22%3A%22Gene+ID%22%2C%22name%22%3A%22SVI_SRSF2_HsclCreYFP_STAR_mm10_rmdup_counts_annotated%22%2C%22primary_name%22%3A%22%22%2C%22init_select%22%3A%5B%22KI%22%2C%22WT%22%5D%2C%22hidden_factor%22%3A%5B%5D%2C%22min_counts%22%3A10%2C%22min_cpm%22%3A1%2C%22min_cpm_samples%22%3A2%7DHTTP/1.1 200 OK
Date: Wed, 30 Aug 2017 05:24:26 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/html
Content-Disposition: inline; filename="compare.html"
Content-Transfer-Encoding: binary
Cache-Control: private
X-Request-Id: 90e1ff14-3615-46b4-9dad-d40abcb724a3
X-Runtime: 0.002492
Set-Cookie: _degust-jobs_session=SHVIU2xJQXEyVVMwOW9nL01DamZySGtpZzhqN3RCNzQ2N3R1UFZJQlQ0Rno0L1U1OUV0M28zVTVURUg2Q1F3MVIza0FnNkR2K2w5WFhJQThkd1krN1ZCT3hIcU1yU01TSXV3VDNTOWlhK3FkTFYwL3dxZm9sQ3dVYXRINHVpaWExeUl6dFZvdEFqQUk2Q09ibTROcElha2VtNVpjWWtoVm1DWDlRRjZSNlFFPS0tWG5uV1NEZ1RNaEszT3FQZktpRjF6dz09--0187109c89db3122880ea03ef96dfd4b1f35b5f4; path=/; HttpOnly
Content-Encoding: gzip
Keep-Alive: timeout=5, max=99
Content-Length: 423
Accept-Ranges: none
Connection: keep-alive

‹������SA’Ó0¼çƒ.>YJ ¸€íð‚}bíÉÊ–JšÄ›¢ø;²­„PÅ.'«¦Õ=3­v5ðh›@5 6àƒëÈb-fÿI©yžåüAºÐ«÷ûýGuØ«|E,¤D³4=C@[jÝ$€¯>ÑiÔ=*?õ†€].DÕéËrM.ˆjv›Ä»²„o/ŒaÒ6Â—§'(Ë?Ô#_-Æ‘³d!U£²t”é[À]îßœÖcb¥mó2¾ð‰Eæõ*^ü›üZ.¶<?â'}Ñ[U@í*·
tŠES©
kÞ@–Úç>ùo…Û.¿ó+µÄb=¹fIC S‹€ÞêË´VÇX‹ô¸¬iÂó‘ogôtŽCÊÉ
]‚wh¾bŽœšê¾©t6<§Ñïf´VöÄÃù(É)³2Uq—Ð
PL9Æ´M=\Ý9€Ñ¬¥”ëKÅ•¡™’óRVÊ?ô¦±¿YsKnššKë´ÁúwÅ}?•ÌÆlÇWø~#Ï47ËˆÌiØ5|‡Ÿ³Øã3lî'‡Ößu÷âO°m·��

**Comment by drpowell** [comment]
That is strange.  I can't reproduce it - can you make it happen regularly?

**Comment by drpowell** [comment]
I can't make this happen.  Closing, but please re-open if it happens regularly
