### ISSUE TITLE
installation behind a proxy?

### ISSUE THREAD

**Issue by xmaksimus** [drpowell/degust#94]
Cannot install due to repo connection issues. Our org is behind a proxy which has been set in the environment and apt (Ubuntu 20.04). Is there any way to define this in the docker build config?

> \# docker build . --tag degust
> Sending build context to Docker daemon  47.65MB
> Step 1/21 : FROM ruby:2.4.6-stretch AS degust-builder
> ---> e488267e6829
> Step 2/21 : RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -     && echo 'deb http://cran.rstudio.org/bin/linux/debian stretch-cran35/' > '/etc/apt/sources.list.d/r-base.list'     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'     && apt-get update     && apt-get install -y nodejs r-base     && rm -rf /var/lib/apt/lists/*
>  ---> Running in d99416e567ef
> 
> \#\# Installing the NodeSource Node.js 10.x repo...
> 
> 
> \#\# Populating apt-get cache...
> 
> \+ apt-get update
> Err:1 http://deb.debian.org/debian stretch InRelease
 >  Could not connect to debian.map.fastlydns.net:80 (151.101.30.132). - connect (111: Connection refused) Unable to connect to deb.debian.org:http:
> Err:2 http://deb.debian.org/debian stretch-updates InRelease
  Unable to connect to deb.debian.org:http:
> Err:3 http://security.debian.org/debian-security stretch/updates InRelease
  Could not connect to debian.map.fastlydns.net:80 (151.101.30.132). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.66.132). - connect (111: Connection refused) [IP: 151.101.66.132 80]
> Reading package lists...
> W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Could not connect to debian.map.fastlydns.net:80 (151.101.30.132). - connect (111: Connection refused) Unable to connect to deb.debian.org:http:
> W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Could not connect to debian.map.fastlydns.net:80 (151.101.30.132). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.66.132). - connect (111: Connection refused) [IP: 151.101.66.132 80]
> W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Unable to connect to deb.debian.org:http:
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> 
> \#\# Installing packages required for setup: apt-transport-https lsb-release...
> 
> \+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1
> Error executing command, exiting
> The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_10.x | bash -     && echo 'deb http://cran.rstudio.org/bin/linux/debian stretch-cran35/' > '/etc/apt/sources.list.d/r-base.list'     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'     && apt-get update     && apt-get install -y nodejs r-base     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by drpowell** [comment]
That's not an issue I've had to deal with before.  Can you configure your docker client using instructions like here:
https://docs.docker.com/network/proxy/

I would hope that both curl and apt-get would use the httpProxy that is passed in when configured this way.

**Comment by xmaksimus** [comment]
Thanks, the docker proxy config resolved the above issue. However, the build process still couldn't contact the GPG keyserver.

> Warning: apt-key output should not be parsed (stdout is not a terminal)
> Executing: /tmp/apt-key-gpghome.4I5MjOCwWC/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key E19F5F87128899B192B1A2C2AD5F960A256A04AF
> gpg: keyserver receive failed: No keyserver available
> The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_10.x | bash -     && echo 'deb http://cran.rstudio.org/bin/linux/debian stretch-cran35/' > '/etc/apt/sources.list.d/r-base.list'     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'     && apt-get update     && apt-get install -y nodejs r-base     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2

I manually tried adding our nameservers into /etc/resolv.conf but this did not resolve the issue. I ended up having to modify the Dockerfile to include our proxy in the keyserver-options as per the following suggestion:

https://unix.stackexchange.com/a/516780

The build process seems to be working correctly now.
